---
- hosts: cent
  gather_facts: no
  remote_user: root

  tasks:
    - name: Create a login
      user:
        name: rom
        password: "{{ 'password' | password_hash('sha512', 'mysecretsalt') }}"
#        groups:
#          - docker
#          - sudo
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
        home: /home/rom  # Defaults to /home/<username>

    - name: Generate SSH-password
      user:
        name: rom
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/rom/.ssh/id_rsa

    - name: authorized key
      authorized_key:
        user: rom
        state: present
        key: "{{ lookup('file', '/home/roman/.ssh/id_rsa.pub') }}"