---
- hosts: cent
  gather_facts: no
  remote_user: root

  tasks:
    - name: Install postfix
      yum:
        name: postfix
        state: installed
      tags: init postfix

    - name: Uninstall postfix
      yum:
        name: postfix
        state: absent
      tags: drop postfix

