---
# tasks file for dnsmasq
  - name: Install dnsmasq server
    yum:
      name: dnsmasq
      state: installed
      update_cache: yes

  - name: Move config
    command: mv /etc/dnsmasq.conf /etc/dnsmasq.conf.bk

  - name: Create new
    template:
              src: etc_dnsmasq.conf.j2
              dest: /etc/dnsmasq.conf
              validate: 'dnsmasq --test --conf-file=%s'

  - name: Service restart
    service:
      name: dnsmasq
      state: restarted
